config/routes.rb
Rails.application.routes.draw do
  resources :massages

  root 'massages#index'

end

app/models/massage.rb
class Massage < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/massages_controller.rb
class MassagesController < ApplicationController
  before_action :set_massage, only: [:show, :edit, :update, :destroy]

  # GET /massages
  # GET /massages.json
  def index
    @massages = Massage.all
  end

  # GET /massages/1
  # GET /massages/1.json
  def show
  end

  # GET /massages/new
  def new
    @massage = Massage.new
  end

  # GET /massages/1/edit
  def edit
  end

  # POST /massages
  # POST /massages.json
  def create
    @massage = Massage.new(massage_params)

    respond_to do |format|
      if @massage.save
        format.html { redirect_to massages_path, notice: 'Massage was successfully created.' }
        format.json { render :show, status: :created, location: @massage }
      else
        format.html { render :new }
        format.json { render json: @massage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /massages/1
  # PATCH/PUT /massages/1.json
  def update
    respond_to do |format|
      if @massage.update(massage_params)
        format.html { redirect_to massages_path, notice: 'Massage was successfully updated.' }
        format.json { render :show, status: :ok, location: @massage }
      else
        format.html { render :edit }
        format.json { render json: @massage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /massages/1
  # DELETE /massages/1.json
  def destroy
    @massage.destroy
    respond_to do |format|
      format.html { redirect_to massages_url, notice: 'Massage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_massage
      @massage = Massage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def massage_params
      params.require(:massage).permit(:name, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/massages_helper.rb
module MassagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Suggestotron</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% flash.each do |name, msg| %>
    <div><%= msg %></div>
<% end %>

<%= yield %>

</body>
</html>

app/views/massages/_form.html.erb
<%= form_for(@massage) do |f| %>
  <% if @massage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@massage.errors.count, "error") %> prohibited this massage from being saved:</h2>

      <ul>
      <% @massage.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/massages/edit.html.erb
<h1>Editing Massage</h1>

<%= render 'form' %>

<%= link_to 'Show', @massage %> |
<%= link_to 'Back', massages_path %>

app/views/massages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>留言板</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @massages.each do |massage| %>
      <tr>
        <td><%= massage.name %></td>
        <td><%= massage.content %></td>
        <td><%= link_to '顯示留言', massage %></td>
        <td><%= link_to '編輯留言', edit_massage_path(massage) %></td>
        <td><%= link_to '刪除留言', massage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新增留言', new_massage_path %>

app/views/massages/new.html.erb
<h1>New Massage</h1>

<%= render 'form' %>

<%= link_to 'Back', massages_path %>

app/views/massages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @massage.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @massage.content %>
</p>

<%= link_to 'Edit', edit_massage_path(@massage) %> |
<%= link_to 'Back', massages_path %>